*******************************************************************************
*     This file (r_sane_filenames.f) was generated from sane_filenames.cmn by makereg v1.01
*     This file was created on Mon Apr  7 08:37:20 2008
*
*     The command used to create this file was:
*     /w/work5403/sane/bhovik/sanetest/Analyzer/SANE/O.Linux/../../../Linux/bin/makereg sane_filenames.cmn -o r_sane_filenames.f -e /dev/null 
*
*     Do not edit this file.
*******************************************************************************

      subroutine r_sane_filenames

      implicit none


*     Registered, but did not occur in a common block:
*     
*     Occurred in a common block, but were not registered:

      include 'sane_filenames.cmn'

c      integer regparmstring
c      external regparmstring

      call regparmstring('sane_report_template_filename',sane_report_template_filename,
     & 'CTP file with bigcal report')
      call regparmstring('sane_report_blockname',sane_report_blockname,0)
      call regparmstring('sane_report_output_filename',sane_report_output_filename,0)
      call regparmstring('sane_pedestal_output_filename',sane_pedestal_output_filename,0)
      call regparmstring('sane_tree_filename',sane_tree_filename,0)
      call regparmstring('sane_calib_matrix_filename',sane_calib_matrix_filename,0)
      call regparmstring('sane_calib_parm_filename',sane_calib_parm_filename,0)
      call regparmstring('sane_debug_output_filename',sane_debug_output_filename,0)
      call regparmstring('sane_bad_chan_list_filename',sane_bad_chan_list_filename,0)

      return
      end
