*******************************************************************************
*     This file (r_sane_data_structures.f) was generated from sane_data_structures.cmn by makereg v1.01
*     This file was created on Mon Apr  7 08:37:21 2008
*
*     The command used to create this file was:
*     /w/work5403/sane/bhovik/sanetest/Analyzer/SANE/O.Linux/../../../Linux/bin/makereg sane_data_structures.cmn -o r_sane_data_structures.f -e /dev/null 
*
*     Do not edit this file.
*******************************************************************************

      subroutine r_sane_data_structures

      implicit none


*     Registered, but did not occur in a common block:
*     
*     Occurred in a common block, but were not registered:

      include 'sane_data_structures.cmn'

c      integer regeventint
c      external regeventint
c      integer regeventintarray
c      external regeventintarray
c      integer regeventrealarray
c      external regeventrealarray

      call regeventintarray('LUCITE_SANE_RAW_PLANE',LUCITE_SANE_RAW_PLANE,(LUCITE_SANE_MAX_HITS),0)
      call regeventintarray('LUCITE_SANE_RAW_COUNTER_NUM',LUCITE_SANE_RAW_COUNTER_NUM,(LUCITE_SANE_MAX_HITS),0)
      call regeventintarray('LUCITE_SANE_RAW_ADC_POS',LUCITE_SANE_RAW_ADC_POS,(LUCITE_SANE_MAX_HITS),0)
      call regeventintarray('LUCITE_SANE_RAW_ADC_NEG',LUCITE_SANE_RAW_ADC_NEG,(LUCITE_SANE_MAX_HITS),0)
      call regeventintarray('LUCITE_SANE_RAW_TDC_POS',LUCITE_SANE_RAW_TDC_POS,(LUCITE_SANE_MAX_HITS),0)
      call regeventintarray('LUCITE_SANE_RAW_TDC_NEG',LUCITE_SANE_RAW_TDC_NEG,(LUCITE_SANE_MAX_HITS),0)
      call regeventint('LUCITE_SANE_RAW_TOT_HITS',LUCITE_SANE_RAW_TOT_HITS,0)
      call regeventint('luc_min_peds',luc_min_peds,0)
      call regeventintarray('luc_ped_num_neg',luc_ped_num_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_sum2_neg',luc_ped_sum2_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_sum_neg',luc_ped_sum_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_limit_neg',luc_ped_limit_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_num_pos',luc_ped_num_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_sum2_pos',luc_ped_sum2_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_sum_pos',luc_ped_sum_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('luc_ped_limit_pos',luc_ped_limit_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_threshold_neg',luc_ped_threshold_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_threshold_pos',luc_ped_threshold_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_mean_neg',luc_ped_mean_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_mean_pos',luc_ped_mean_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_rms_neg',luc_ped_rms_neg,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventrealarray('luc_ped_rms_pos',luc_ped_rms_pos,(LUCITE_SANE_MAX_COUNTER_NUM),0)
      call regeventintarray('CERENKOV_SANE_RAW_PLANE',CERENKOV_SANE_RAW_PLANE,(CERENKOV_SANE_MAX_HITS),0)
      call regeventintarray('CERENKOV_SANE_RAW_COUNTER_NUM',CERENKOV_SANE_RAW_COUNTER_NUM,(CERENKOV_SANE_MAX_HITS),0)
      call regeventintarray('CERENKOV_SANE_RAW_ADC',CERENKOV_SANE_RAW_ADC,(CERENKOV_SANE_MAX_HITS),0)
      call regeventintarray('CERENKOV_SANE_RAW_TDC',CERENKOV_SANE_RAW_TDC,(CERENKOV_SANE_MAX_HITS),0)
      call regeventint('CERENKOV_SANE_RAW_TOT_HITS',CERENKOV_SANE_RAW_TOT_HITS,0)
      call regeventint('cer_sane_min_peds',cer_sane_min_peds,0)
      call regeventintarray('cer_sane_ped_num',cer_sane_ped_num,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventintarray('cer_sane_ped_sum2',cer_sane_ped_sum2,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventintarray('cer_sane_ped_sum',cer_sane_ped_sum,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventintarray('cer_sane_ped_limit',cer_sane_ped_limit,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventrealarray('cer_sane_ped_threshold',cer_sane_ped_threshold,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventrealarray('cer_sane_ped_mean',cer_sane_ped_mean,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventrealarray('cer_sane_ped_rms',cer_sane_ped_rms,(CERENKOV_SANE_MAX_CER_COUNTER),0)
      call regeventintarray('TRACKER_SANE_RAW_PLANE_Y',TRACKER_SANE_RAW_PLANE_Y,(TRACKER_SANE_MAX_HITS),0)
      call regeventintarray('TRACKER_SANE_RAW_PLANE_X',TRACKER_SANE_RAW_PLANE_X,(TRACKER_SANE_MAX_HITS),0)
      call regeventintarray('TRACKER_SANE_RAW_COUNTER_Y',TRACKER_SANE_RAW_COUNTER_Y,(TRACKER_SANE_MAX_HITS),0)
      call regeventintarray('TRACKER_SANE_RAW_COUNTER_X',TRACKER_SANE_RAW_COUNTER_X,(TRACKER_SANE_MAX_HITS),0)
      call regeventintarray('TRACKER_SANE_RAW_TDC_Y',TRACKER_SANE_RAW_TDC_Y,(TRACKER_SANE_MAX_HITS),0)
      call regeventintarray('TRACKER_SANE_RAW_TDC_X',TRACKER_SANE_RAW_TDC_X,(TRACKER_SANE_MAX_HITS),0)
      call regeventint('TRACKER_SANE_RAW_TOT_HITS_Y',TRACKER_SANE_RAW_TOT_HITS_Y,0)
      call regeventint('TRACKER_SANE_RAW_TOT_HITS_X',TRACKER_SANE_RAW_TOT_HITS_X,0)

      return
      end
