#
# $Log$
# Revision 1.11  2008/09/25 00:07:29  jones
# Updated to run with gfortran compiler
#
# Revision 1.10  1999/01/21 21:39:29  saw
# Clean up Include file rules
#
# Revision 1.9  1998/12/09 16:31:16  saw
# Remove dependence on Csoft environment variable
#
# Revision 1.8  1998/12/07 22:11:19  saw
# Initial setup
#
# Revision 1.7  1996/09/04 15:41:55  saw
# (SAW) Fixes for linux
#
# Revision 1.6  1996/04/30 12:30:51  saw
# (SAW) New makefile style
#
# Revision 1.5  1996/01/16 21:29:41  cdaq
# (SAW) Use $(CP) instead of cp
#
# Revision 1.4  1995/07/28 14:19:08  cdaq
# (SAW) Add NFSDIRECTORY stuff
#
# Revision 1.3  1995/03/13  18:43:38  cdaq
# (SAW) Add -f switch on include file copy commands
#
# Revision 1.2  1995/01/27  20:51:03  cdaq
# SAW) Remove RCS from include file rules
#
# Revision 1.1  1994/07/25  18:03:10  cdaq
# Initial revision
#
NEWSTYLE = 1
include ../../etc/Makefile
include ../../etc/Makefile.flags

hack_source = hack_register_variables.f hack_initialize.f hack_anal.f \
	 hack_shutdown.f hack_copyevt.f r_hack_.f

libsources =  $(hack_source)

sources = $(libsources)

lib_targets := $(patsubst %.f, libhack.a(%.o), $(sources))

install-dirs := lib
bin_targets =

#default:
#	@echo "nothing to make"

#
# Rule for making the register subroutines
#
../r_%.f : ../%.cmn $(MAKEREG)
	(cd .. ; $(MAKEREG) $(<F) -o $(@F) -e /dev/null)

.PRECIOUS: ../r_%.f

ifdef NFSDIRECTORY
../%.f : $(NFSDIRECTORY)/HACK/%.f
	ln -s $< $@

.PRECIOUS: ../%.f
endif

%.cmn ../%.cmn:: ../../INCLUDE/%.cmn
	$(CP) $< $@

include $(sources:.f=.d)
