#
# $Log$
# Revision 1.2  1995/01/27 20:51:03  cdaq
# SAW) Remove RCS from include file rules
#
# Revision 1.1  1994/07/25  18:03:10  cdaq
# Initial revision
#
include $(Csoft)/etc/Makefile

hack_source = hack_register_variables.f hack_initialize.f hack_anal.f \
	 hack_shutdown.f hack_copyevt.f

libsources =  $(hack_source)

sources = $(libsources)

lib_targets := $(patsubst %.f, libhack.a(%.o), $(sources))

install-dirs := lib

default:
	@echo "nothing to make"

%.cmn :: ../INCLUDE/%.cmn
	cp $< $@

include $(sources:.f=.d)
