#
# $Log$
# Revision 1.1.2.1  2008/10/25 12:49:15  cdaq
# *** empty log message ***
#
# Revision 1.1.2.1  2008/05/07 18:13:53  bhovik
# starting files
#
# Revision 1.1.2.1  2007/05/15 01:19:10  jones
# Start to Bigcal code
#
# Revision 1.1  1998/12/08 14:33:24  saw
# Initial Setup
#
ETC=../etc

include $(ETC)/Makefile.NEW
